<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS1591;CS1998</NoWarn>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <Authors>Manuel Jhobanny Morillo Ordoñez</Authors>
    <Company>Manuel Jhobanny Morillo Ordoñez</Company>
    <Product>CrocManager</Product>
    <Description>Interfaz gráfica para croc - Transferencia segura de archivos</Description>
    <Copyright>© 2026 Manuel Jhobanny Morillo Ordoñez</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3065.39" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WebDesktop.Core">
      <HintPath>lib\WebDesktop.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
